### PR TITLE
:sparkles: Adding ability to specify idempotency token in write transaction

### PR DESCRIPTION
**Pull request by greggjs**
Currently, you cannot specify a client token for Dynamo transactions. This PR adds that functionality through a new method to the `WriteTx` struct

```golang
IdempotentWithToken(enabled bool, token string) *WriteTx
```

This method will use the token provided, only if it is not blank. If it is not blank and enabled, it will use that token for requests.

### CODE REVIEW

**Comment by guregu** [comment]
Thanks for the clean PR and test code.
Personally I’d get rid of the boolean parameter since a blank string or the other Idempotent method takes care of turning it off.
Before I merge this could I ask what the use case for wanting to specify for own token is?

**Comment by greggjs** [comment]
Yea that's fine to do if that's OK with you, I was just trying to keep in the paradigm of the other method, where you can pass in if you want it to be idempotent or not.

So the reason why I'd want my own token is if I'm using Dynamo transactions from an application level to execute transactions. Having clients pass in a Transaction ID, you can use this to ensure idempotency of updates from your Dynamo Transaction record.

**Comment by guregu** [comment]
Sorry, could you be more specific on why auto-generated IDs wouldn't work? I'm not really sure what you mean. 
I'm only asking because I want to avoid exposing as many internals as possible with this library to make it as easy to use as possible. Of course if there's a valid use case I'd be happy to add this.

**Comment by guregu** [comment]
@greggjs @benjamindow Sorry for wait, this is released in v1.5.0. I simplified the API a bit.

**Pull request merged**
