### PR TITLE
dynamo v2: featuring aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by guregu**
(This is a continuation of #206, fresh PR without merge conflicts).

At last, the long awaited dynamo/v2! This keeps mostly the same API as v1 but uses the new AWS SDK.

Changes:
- All operations require a `context.Context` now, removed `...WithContext` methods
- Uses `int` instead of `int64` for limits
- `PagingIter.LastEvaluatedKey` can return an error now (in exceedingly rare circumstances, but better safe than sorry)
  - No need for a debug logger anymore because of this
- `KMSMasterKeyArn`  renamed to `KMSMasterKeyARN`
- Request retrying relies on the AWS client now, and can be configured using its options

I believe v2 should be **ready for testing** now. You can try it out now with:
```console
go get github.com/guregu/dynamo/v2@v2-dev
```

I would really appreciate it if people test it before the official release.
I will release this after I get some feedback. Or, if I don't get any, within a few weeks.

### CODE REVIEW

**Comment by sgriffith3** [comment]
@guregu Any reason you are holding this PR open any longer?

**Comment by guregu** [comment]
> @guregu Any reason you are holding this PR open any longer?

There were some encoding bugs that should hopefully be all taken care of now, haven't heard anything new. Has anyone tried running this (even against their test suite)? Would be nice to get some feedback.

**Comment by sgriffith3** [comment]
My team has prioritized testing this on our infrastructure for you. We will be able to work on this over the next several business days.

Are there any specific tests that you would like us to run for this, or just generally make sure it is working as expected?

**Comment by sgriffith3** [comment]
Unfortunately, our use case does not include custom encoding nor practically any concurrent modification. But I can confirm that running it on our code base works as expected!

**Comment by guregu** [comment]
That is good news, thanks. It looks like we are ready then. I'll make the release this week, within a day or two, as soon as I get some free time.

**Pull request merged**
